### ISSUE TITLE
Add release builds for intel macs

### ISSUE THREAD

**Issue by sbhal** [unobserved-io/espanso-gui#2]

**Comment by rickykresslein** [comment]
I would love to put out a release for intel macs, but unfortunately I don't have one. I can try to build one in a VM, but that can be a pain with macOS. If you or anyone reading this has an Intel Mac, you can clone this repository and then run `cargo bundle --release` (first install cargo-bundle with `cargo install cargo-bundle`). That will create a bundle. If you can then get that to me I will add it to the releases.

**Comment by rickykresslein** [comment]
Thank you @sbhal for creating a build for Intel Macs!
