### ISSUE TITLE
Dark theme, follow system theme

### ISSUE THREAD

**Issue by xplosionmind** [unobserved-io/espanso-gui#4]
The light theme of the app is terribly itchy when the rest of the system has dark mode enabled… it would be nice if the app had one too, following system settings.

**Comment by rickykresslein** [comment]
I will definitely look into this. This is my first time using Iced, so I'm learning how they do things as I go. What operating system are you using?

**Comment by rickykresslein** [comment]
It should be fixed now on all operating systems. It will match the system theme when opened, but if you change the system theme while using espansoGUI, you will need to close and re-open the app to change it.
