### ISSUE TITLE
Pasting/Typing in Word Delimiter ("Word Separator") text box in GUI causes instant crash without hang-up; able to click no problem, only key strokes appear to be an issue (including negative or nonpositive character keystrokes)

### ISSUE THREAD

**Issue by iotaOmicron** [unobserved-io/espanso-gui#6]
I've just been trying this, and it hasn't been too long, but i did use espanso for a while previously.

I've noticed that when trying to set the app  settings up, pasting or typing into the box for defining delimiters causes an immediate crash, and I have to reopen the GUI. Unsure if this is affecting text expansion or not as i haven't gotten that set up yet. the text box is fine if i click on it, but as soon as i press a keyboard key, the GUI disappears.

mbp 16" on macOS Ventura ~13.5

of course, the wanted/expected behavior would obviously be that i am able to edit text boxes without crashing. 

Another issue with this is i can't seem to find where in the configuration files the delimiters are outlined, so i can't fix this manually. Not a huge problem though, i'm loving the app. using a text file to keep up with the # of new expansions i make was drag. hopefully the main app (espanso) has been updated since then, because one of the reasons i had to switch off of it was that it was just slightly too slow to keep up, but it was still in the upper half. weird problem for a typing tool to have, but it makes sense, and almost every other expander tool has more hiccoughs than espanso

**Comment by lakoliu** [comment]
Wow thanks for bringing this to my attention. I am definitely able to reproduce it so I will get to work on this immediately. Glad to hear you are enjoying the app!

**Comment by rickykresslein** [comment]
This should be fixed with 015ee7f, but there could still be some bugs in the Word Separators config option. Please let me know if you find any more.
