### ISSUE TITLE
Cant launch window

### ISSUE THREAD

**Issue by nosar77** [unobserved-io/espanso-gui#9]
Lenovo Legion 5
EndeavourOS
Gnome 46
Wayland
Linux Kernel 6.8.8-arch1-1

[espanso-wayland-git](https://aur.archlinux.org/packages/espanso-wayland-git)	2.2.0.r64.gd99e5d9-4
[espanso-gui](https://aur.archlinux.org/packages/espanso-gui)	23.10-1

Im trying to run Espanso-gui and the program doesnt open running it in the terminal results in this error

`interface 'wl_surface' has no event 2`

**Comment by rickykresslein** [comment]
Thank you. Sorry for the delay in my response. I will look into this. Thank you for providing all of your system details.

**Comment by Anagastes** [comment]
Can confirm this issue.

But same with no git packages
espanso-wayland 2.2.1-4
espanso-gui 23.10-1

```
Operating System: EndeavourOS 
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.6.32-1-lts (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-4670 CPU @ 3.40GHz
Memory: 23.4 GiB of RAM
Graphics Processor: AMD Radeon RX 570 Series
Manufacturer: ASUS
Product Name: All Series
```

**Comment by rickykresslein** [comment]
I've looked a lot more into this and it seems to be a dependency issue, possibly with smithay. I am going to update espanso-gui in the coming days (it may take a bit because Iced has changed significantly in the past year), which should fix this bug. For now, you should be able to install the Flatpak to use espansoGUI. Thank you for your patience.

**Comment by rickykresslein** [comment]
Version 24.7 has been updated to use the latest version of Iced and should fix this issue. Once the AUR maintainer has updated it, please let me know if you have any more issues.
